import type { ILoggerAdapter } from "@/infra/logger";
import type { ApiTracingInput } from "@/utils/request";
import type { IUsecase } from "@/utils/usecase";
import { type Infer, InputValidator, ValidateSchema } from "@/utils/validator";

import { LogEntity } from "../entity/log";
import type { ILogRepository } from "../repository/log";

export const LogCreateSchema = InputValidator.object({
  message: InputValidator.string().trim().min(1),
  type: InputValidator.enum(["input", "output"]),
  flowId: InputValidator.number().int().positive().nullish(),
});

export type LogCreateInput = Infer<typeof LogCreateSchema>;
export type LogCreateOutput = LogEntity;

export class LogCreateUsecase implements IUsecase {
  constructor(
    private readonly logRepository: ILogRepository,
    private readonly loggerService: ILoggerAdapter,
  ) {}

  @ValidateSchema(LogCreateSchema)
  async execute(
    input: LogCreateInput,
    { tracing }: ApiTracingInput,
  ): Promise<LogCreateOutput> {
    const entity = new LogEntity({
      id: 1, // Auto-generated by database
      message: input.message,
      type: input.type as "input" | "output",
      flowId: input.flowId ?? null,
      createdAt: new Date(),
    });

    const log = await this.logRepository.create(entity);

    this.loggerService.info({
      message: "log created successfully",
      obj: { log },
    });

    tracing.logEvent("log-created", `log: ${log.id} created`);

    return log;
  }
}
