apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: nestjs-microservice
    user: postgres
    secureJsonData:
      password: postgres
    editable: true
    jsonData:
      sslmode: disable
      timescaledb: false

